#!/usr/bin/env python3
"""
rapp_copilot_in_chrome_agent.py -- install, verify, and diagnose the Chrome
browser-automation bridge that lets GitHub Copilot CLI drive real Chrome.

Stdlib only, Python 3.9+. No framework, no install step.

    python3 rapp_copilot_in_chrome_agent.py '{"action": "doctor"}'
    echo '{"action": "install"}' | python3 rapp_copilot_in_chrome_agent.py
    python3 rapp_copilot_in_chrome_agent.py --tool

Companion to SKILL.md, which carries the browser-usage guide. See
https://github.com/kody-w/rapp-copilot-in-chrome
"""

import json
import os
import shutil
import subprocess
import sys
import threading
import time

try:
    from agents.basic_agent import BasicAgent
except ImportError:  # running OUTSIDE the brainstem -- stay executable anyway.
    class BasicAgent:
        def __init__(self, name=None, metadata=None):
            if name:
                self.name = name
            if metadata:
                self.metadata = metadata

        def perform(self, **kwargs):
            return "Not implemented."

        def system_context(self):
            return None

        def to_tool(self):
            return {"type": "function", "function": {
                "name": self.name,
                "description": self.metadata.get("description", ""),
                "parameters": self.metadata.get("parameters", {})}}

__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@rapp/rapp_copilot_in_chrome_agent",
    "version": "1.0.0",
    "display_name": "RAPP Copilot in Chrome",
    "description": "Install, verify, and diagnose the Chrome browser-automation bridge for Copilot CLI.",
    "author": "kody-w",
    "tags": ["browser", "chrome", "mcp", "automation", "copilot-cli"],
    "category": "integrations",
    "quality_tier": "official",
    "requires_env": [],
    "example_call": "Check whether rapp-copilot-in-chrome is installed and the browser bridge is healthy.",
}

EXTENSION_ID = "fcoeoabgfenejglbffodgkkbkcdhcgfn"
NATIVE_HOST = "com.anthropic.claude_code_browser_extension"
SERVER_NAME = "rapp-copilot-in-chrome"

HOME = os.path.expanduser("~")
COPILOT_DIR = os.path.join(HOME, ".copilot")
BIN_PATH = os.path.join(COPILOT_DIR, "bin", SERVER_NAME)
MCP_CONFIG = os.path.join(COPILOT_DIR, "mcp-config.json")
SKILL_DIR = os.path.join(COPILOT_DIR, "skills", SERVER_NAME)

LAUNCHER = """#!/bin/sh
# rapp-copilot-in-chrome -- stdio MCP server bridging Copilot CLI to Chrome.
# Generated by rapp_copilot_in_chrome_agent.py
# https://github.com/kody-w/rapp-copilot-in-chrome
set -e

if [ -n "$RAPP_CHROME_CLAUDE_BIN" ] && [ -x "$RAPP_CHROME_CLAUDE_BIN" ]; then
  CLAUDE_BIN="$RAPP_CHROME_CLAUDE_BIN"
elif [ -x "$HOME/.local/bin/claude" ]; then
  CLAUDE_BIN="$HOME/.local/bin/claude"
else
  CLAUDE_BIN="$(command -v claude 2>/dev/null || true)"
fi

if [ -z "$CLAUDE_BIN" ] || [ ! -x "$CLAUDE_BIN" ]; then
  echo "rapp-copilot-in-chrome: cannot locate the 'claude' binary that hosts the browser bridge." >&2
  echo "Install Claude Code, or set RAPP_CHROME_CLAUDE_BIN to its absolute path." >&2
  exit 127
fi

exec "$CLAUDE_BIN" --claude-in-chrome-mcp
"""


def _claude_bin():
    """Resolve the Claude binary that hosts the browser bridge."""
    env = os.environ.get("RAPP_CHROME_CLAUDE_BIN")
    if env and os.access(env, os.X_OK):
        return env
    local = os.path.join(HOME, ".local", "bin", "claude")
    if os.access(local, os.X_OK):
        return local
    return shutil.which("claude")


def _native_host_manifests():
    """Every native-messaging manifest registering the bridge, across Chromium forks."""
    if sys.platform == "darwin":
        root = os.path.join(HOME, "Library", "Application Support")
        bases = {
            "Chrome": ["Google", "Chrome"],
            "Chrome Beta": ["Google", "Chrome Beta"],
            "Chrome Canary": ["Google", "Chrome Canary"],
            "Chromium": ["Chromium"],
            "Brave": ["BraveSoftware", "Brave-Browser"],
            "Edge": ["Microsoft", "Edge"],
        }
    elif sys.platform.startswith("linux"):
        root = os.path.join(HOME, ".config")
        bases = {
            "Chrome": ["google-chrome"],
            "Chromium": ["chromium"],
            "Brave": ["BraveSoftware", "Brave-Browser"],
            "Edge": ["microsoft-edge"],
        }
    else:
        return []

    found = []
    for label, parts in bases.items():
        path = os.path.join(root, *parts, "NativeMessagingHosts", NATIVE_HOST + ".json")
        if os.path.exists(path):
            found.append({"browser": label, "path": path})
    return found


def _extension_installed():
    """True if the extension directory exists in any profile of any Chromium fork."""
    if sys.platform == "darwin":
        roots = [os.path.join(HOME, "Library", "Application Support", "Google", "Chrome"),
                 os.path.join(HOME, "Library", "Application Support", "Chromium"),
                 os.path.join(HOME, "Library", "Application Support", "BraveSoftware",
                              "Brave-Browser")]
    elif sys.platform.startswith("linux"):
        roots = [os.path.join(HOME, ".config", "google-chrome"),
                 os.path.join(HOME, ".config", "chromium"),
                 os.path.join(HOME, ".config", "BraveSoftware", "Brave-Browser")]
    else:
        return False

    for root in roots:
        if not os.path.isdir(root):
            continue
        try:
            for profile in os.listdir(root):
                if os.path.isdir(os.path.join(root, profile, "Extensions", EXTENSION_ID)):
                    return True
        except OSError:
            continue
    return False


def _read_mcp_config():
    if not os.path.exists(MCP_CONFIG):
        return {}
    try:
        with open(MCP_CONFIG, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except (ValueError, OSError):
        return {}


def _probe(timeout=45, live=False):
    """Speak MCP over stdio to the bridge.

    Returns a dict with the tool count and, when live=True, a real round trip
    through Chrome proving tabs are reachable.
    """
    if os.access(BIN_PATH, os.X_OK):
        argv = [BIN_PATH]
    else:
        claude = _claude_bin()
        if not claude:
            return {"ok": False, "error": "no launcher and no claude binary found"}
        argv = [claude, "--claude-in-chrome-mcp"]

    try:
        proc = subprocess.Popen(argv, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE, text=True, bufsize=1)
    except OSError as exc:
        return {"ok": False, "error": "could not start bridge: %s" % exc}

    threading.Thread(target=lambda: [None for _ in proc.stderr], daemon=True).start()

    def send(obj):
        proc.stdin.write(json.dumps(obj) + "\n")
        proc.stdin.flush()

    def wait(msg_id, budget):
        deadline = time.time() + budget
        while time.time() < deadline:
            line = proc.stdout.readline()
            if not line:
                return None
            try:
                msg = json.loads(line)
            except ValueError:
                continue
            if msg.get("id") == msg_id:
                return msg
        return None

    out = {"ok": False}
    try:
        send({"jsonrpc": "2.0", "id": 1, "method": "initialize", "params": {
            "protocolVersion": "2025-06-18", "capabilities": {},
            "clientInfo": {"name": "rapp-copilot-in-chrome-doctor", "version": "1.0.0"}}})
        send({"jsonrpc": "2.0", "method": "notifications/initialized"})
        init = wait(1, timeout)
        if not init:
            return {"ok": False, "error": "bridge did not answer initialize"}
        out["server"] = init.get("result", {}).get("serverInfo", {})

        send({"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}})
        listed = wait(2, timeout)
        if not listed:
            return {"ok": False, "error": "bridge did not answer tools/list"}
        tools = listed.get("result", {}).get("tools", [])
        out["tool_count"] = len(tools)
        out["tools"] = sorted(t["name"] for t in tools)
        out["ok"] = True

        if live:
            send({"jsonrpc": "2.0", "id": 3, "method": "tools/call", "params": {
                "name": "tabs_context_mcp", "arguments": {"createIfEmpty": True}}})
            ctx = wait(3, timeout)
            if ctx and not ctx.get("result", {}).get("isError"):
                out["browser_connected"] = True
                out["tab_context"] = ctx["result"]["content"][0].get("text", "")[:400]
            else:
                out["browser_connected"] = False
                out["browser_error"] = "tabs_context_mcp failed; extension may be disconnected"
    finally:
        try:
            proc.kill()
        except OSError:
            pass
    return out


def _do_install(skill_src_dir):
    steps = []

    os.makedirs(os.path.dirname(BIN_PATH), exist_ok=True)
    with open(BIN_PATH, "w", encoding="utf-8") as fh:
        fh.write(LAUNCHER)
    os.chmod(BIN_PATH, 0o755)
    steps.append("wrote launcher %s" % BIN_PATH)

    cfg = _read_mcp_config()
    cfg.setdefault("mcpServers", {})[SERVER_NAME] = {
        "type": "local", "command": BIN_PATH, "args": [], "tools": ["*"]}
    os.makedirs(COPILOT_DIR, exist_ok=True)
    with open(MCP_CONFIG, "w", encoding="utf-8") as fh:
        json.dump(cfg, fh, indent=2)
        fh.write("\n")
    steps.append("registered MCP server '%s' in %s" % (SERVER_NAME, MCP_CONFIG))

    if skill_src_dir and os.path.isdir(skill_src_dir):
        copied = []
        os.makedirs(SKILL_DIR, exist_ok=True)
        for name in ("SKILL.md", os.path.basename(os.path.abspath(__file__))):
            src = os.path.join(skill_src_dir, name)
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(SKILL_DIR, name))
                copied.append(name)
        if copied:
            steps.append("installed skill (%s) to %s" % (", ".join(copied), SKILL_DIR))

    return steps


def _do_uninstall():
    steps = []
    cfg = _read_mcp_config()
    if cfg.get("mcpServers", {}).pop(SERVER_NAME, None) is not None:
        with open(MCP_CONFIG, "w", encoding="utf-8") as fh:
            json.dump(cfg, fh, indent=2)
            fh.write("\n")
        steps.append("unregistered MCP server '%s'" % SERVER_NAME)
    if os.path.exists(BIN_PATH):
        os.remove(BIN_PATH)
        steps.append("removed launcher %s" % BIN_PATH)
    if os.path.isdir(SKILL_DIR):
        shutil.rmtree(SKILL_DIR)
        steps.append("removed skill %s" % SKILL_DIR)
    return steps or ["nothing to remove; already uninstalled"]


class RappCopilotInChromeAgent(BasicAgent):
    def __init__(self):
        self.name = "RappCopilotInChrome"
        self.metadata = {
            "name": self.name,
            "description": (
                "Install, verify, and diagnose the rapp-copilot-in-chrome browser bridge "
                "that lets GitHub Copilot CLI drive the user's real, logged-in Chrome. "
                "Use when setting it up, when browser tools are missing or failing, or "
                "when the user asks whether the Chrome bridge is working."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "action": {
                        "type": "string",
                        "description": (
                            "What to do. 'doctor' (default) runs every check including a "
                            "live round trip through Chrome. 'status' is a fast check with "
                            "no browser traffic. 'install' writes the launcher, registers "
                            "the MCP server, and installs the skill. 'uninstall' removes "
                            "all three."
                        ),
                        "enum": ["doctor", "status", "install", "uninstall"],
                    },
                    "skill_dir": {
                        "type": "string",
                        "description": (
                            "Directory holding SKILL.md to install alongside the server. "
                            "Defaults to the directory containing this file."
                        ),
                    },
                    "timeout": {
                        "type": "integer",
                        "description": "Seconds to wait for the bridge to answer. Default 45.",
                        "minimum": 5,
                        "maximum": 300,
                    },
                },
                "required": [],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):
        action = (kwargs.get("action") or "doctor").strip().lower()
        if action not in ("doctor", "status", "install", "uninstall"):
            return json.dumps({
                "status": "error",
                "message": "action must be one of: doctor, status, install, uninstall"})

        try:
            timeout = int(kwargs.get("timeout") or 45)
        except (TypeError, ValueError):
            timeout = 45
        timeout = max(5, min(300, timeout))

        skill_dir = kwargs.get("skill_dir") or os.path.dirname(os.path.abspath(__file__))

        if action == "uninstall":
            steps = _do_uninstall()
            return json.dumps({
                "status": "success", "action": "uninstall", "steps": steps,
                "summary": "Uninstalled.\n\n" + "\n".join("- " + s for s in steps)})

        steps = []
        if action == "install":
            try:
                steps = _do_install(skill_dir)
            except OSError as exc:
                return json.dumps({"status": "error", "message": "install failed: %s" % exc})

        claude = _claude_bin()
        manifests = _native_host_manifests()
        extension = _extension_installed()
        registered = SERVER_NAME in _read_mcp_config().get("mcpServers", {})
        launcher_ok = os.access(BIN_PATH, os.X_OK)

        checks = [
            {"check": "claude binary (hosts the bridge)", "ok": bool(claude),
             "detail": claude or "not found -- install Claude Code or set RAPP_CHROME_CLAUDE_BIN"},
            {"check": "native messaging host manifest", "ok": bool(manifests),
             "detail": ", ".join(m["browser"] for m in manifests) or
                       "not registered -- launch Claude Code once to install it"},
            {"check": "Chrome extension %s" % EXTENSION_ID, "ok": extension,
             "detail": "installed" if extension
                       else "not found -- install the Claude in Chrome extension"},
            {"check": "launcher %s" % BIN_PATH, "ok": launcher_ok,
             "detail": "executable" if launcher_ok else "missing -- run action 'install'"},
            {"check": "MCP server registered", "ok": registered,
             "detail": ("registered in %s" % MCP_CONFIG) if registered
                       else "not registered -- run action 'install'"},
        ]

        probe = {}
        if action in ("doctor", "install"):
            probe = _probe(timeout=timeout, live=True)
            checks.append({
                "check": "bridge answers MCP", "ok": bool(probe.get("ok")),
                "detail": ("%d tools" % probe["tool_count"]) if probe.get("ok")
                          else probe.get("error", "no response")})
            if probe.get("ok"):
                checks.append({
                    "check": "Chrome reachable (live round trip)",
                    "ok": bool(probe.get("browser_connected")),
                    "detail": "tab group reachable" if probe.get("browser_connected")
                              else probe.get("browser_error", "no browser response")})

        healthy = all(c["ok"] for c in checks)
        summary = "\n".join(
            "%s %s -- %s" % ("[ok]" if c["ok"] else "[!!]", c["check"], c["detail"])
            for c in checks)
        if steps:
            summary = "Installed:\n" + "\n".join("- " + s for s in steps) + "\n\n" + summary
        if healthy:
            summary += ("\n\nHealthy. Restart Copilot CLI, then load the tools with a single "
                        "tool search for \"rapp-copilot-in-chrome\".")
        else:
            summary += "\n\nSome checks failed -- see the details above."

        return json.dumps({
            "status": "success" if healthy else "degraded",
            "action": action,
            "steps": steps,
            "checks": checks,
            "tools": probe.get("tools", []),
            "summary": summary,
            "data_slush": {
                "healthy": healthy,
                "tool_count": probe.get("tool_count", 0),
                "browser_connected": probe.get("browser_connected"),
            },
        })


if __name__ == "__main__":
    # Standalone entry point -- no brainstem, no framework, no install.
    #     python3 rapp_copilot_in_chrome_agent.py '{"action": "doctor"}'
    #     echo '{"action": "install"}' | python3 rapp_copilot_in_chrome_agent.py
    #     python3 rapp_copilot_in_chrome_agent.py --tool
    _args = sys.argv[1:]
    if _args and _args[0] == "--tool":
        print(json.dumps(RappCopilotInChromeAgent().to_tool(), indent=2))
    else:
        _raw = _args[0] if _args else (sys.stdin.read().strip() or "{}")
        print(RappCopilotInChromeAgent().perform(**json.loads(_raw)))

# rci-capsule:v1:H4sIAAAAAAAC/+09a3PbRpJ/ZUKfIzIhIdmJd/eY09Y5sjZWrSO7LCe3VRILNQSGJCwQ4GIAyVxH99u3HzPA4EXKj7r7Iiu28Jjp6enp7ukXJh8HsshXaTaYJkUcjwehyqIbmUdpMphezvBeB1m04QeDs0TnEpqJG2i22I6FTEIRRnKZpFqJfKVEJjebSZBuojjNJ1EyCVZZulZinqW3WmXwOwqX2FLmIla5Fr9E+ctiLk64hzh5dSZCwICBFdDlQItMSRgyTpdLFQJMcUIwPfEbjHm7UonQKs+jZCmiXBSbMT+zI+ZpGmshMyXWkdbYKs3EQkYxXI7xmlrb0YTU1xofwYOMnp7YCRDiEbxMs2vo6w3GA/VBrjex0kyqFbTbyKWypIzg3WD6cRDEUkOTwVsgjZnnWcJgny9VkgOgWCZLaLHZwlIkcL9R2SLN1vAoVAth7oZaxYux+O6761uZLfVoepUI80cGuEDiWAz5nbdU+fBqwI+vBiOc59UgTIM8zeDW0zms6XDkxemtyoajClC0sLASWA2g9bDqNgYQsPx5ofk6YmbgmyIpb13E8E+m8iJLxHudJl5YrDd6+LHeAP9UoKdwrbKMRuxqt1ZaA5W5oUF2XehczJVIE/i7mApGeSwY5lhElm8dNO9g2hX8PNs20M6jtUqLHIgaJXmdruaVIeyPzxwCqg+B2uRi+G67Uac4i7H4XcYFX496h/jxmYNK+XQtPwyfjYFxk+EPR0dj+2ZUw1xfR3Hsh1EGHWpYli8Mnqn2NjJfefAkkWs1tPdyrvH30PcXUax8vw6+4ojj4/o6Nyajc7XRgIMfpn7ZyuWtz+QFXQQBLDmzmeXoaR0VZk0YH9/QRSfr6GK9ltmWu/9mu6vQu4IZw38D8T28oCvvfQpUvxpMBD3VAiQQ/gWJIPCjOvfYuV/OegnXR7Y24zWJaUlZrmeDpoblXl8Qj4EGwycdMLto3yl1TSEzCJDWVOFUPIb24jGOUqcCKLoiVIg1X/lzIKGD7Fom0ULpnCaWwCZzo/xVqnO/fDGsSVKuEs1qzS9v/HLR3LaZWkZAskyF0Pji9O3vp2/98+e/nuJ6+bB9hP462PhBmiyiJag9lg94dKEy2MmItz7eOfAA/SSAHcBPrwEgCIokHhz+fHbuv3n+7uUYn/3Df/33+vxXKrgmNqgTH8hMr5iahkpAG2BFMUQCaNppeIsZ8QKk1HoOm9eQO4yaHA2KWeWwItjOwCQtj4p7kRawMU8mVvGJE25wknIr2DDF2+dv3vgnL9++/vXUP3n1/LcXpz5MD/TieBf2vGyC+QN3U8S/XNkW7uXK7kSfu7HIrS+vBmbvvhrMSOzWuIwVJJhAm7lLqDh9hx2ABryYdRIkAVgYaUmeKN83b2MGVExphOD0H+9Ozy/OXp/7Zy+quZfNds+65GUABeqi7NU7PRWDydOzxGSs8BxLG8kBuWd+luPtvCpOt3NyZGL3rNQHFRS5nMeKp+UKk5mANcUA/axIrJ48MFM52IfsrydvgIVRdJ2ldnmveroLVdABDqdE5ZoCeP/k9fnfzn4ZIf7OEPdYlzrv7Z/dzNUgmyydowL9eNe1j7TNsV6bywLy6WJoDIdj8xuMaRDi43dZoRp7CaswDyxVlYTde7OzDsYolokGM1Ij3VoKgMY3Chcfj0adO3NtUR6HbLXTYhAA0An4BDR4kYCozmhdWqB7l8eukNvD2eySFFZNb9JEA8eO7hpwukbq2F33Uq5FPSOisD0FK5QWMcRVERkJNhroo04LmOH0kNhoTtzqEhXkKBWdFG9LLQisWMLYmwohFt994HdRvZPyFkh9Bay/1liJCvoKvMB8tQWmRmMouGQa8A4RoGzwCjj4GHNPHDeMuqROhccaBB+F1Yg/oHiZXs949tU4RsYvv/lmhkjjC7OYM76z1Jw1SNKPIMAnQ69pSTt4n9ktYvqJBmrZ0nSztq87uCFpz/DfHyMpGMRLbumJt7AFyyx3HfYxbj0J+OcypE2IPe7bKF8JKVDNx0i3fjZh2QaFLjPYpnEaV1egmTsDCfjGqzEdLkv/BCz+Fyhpxj5jMxYXXCuOM/DKaSHn6Y3yEFfXtNzjsfR4Kw59LeuEapnJkHaqJojKr+GrcXuMHd6N4UR6z1etBkahTmuSaB6OwW8ZtUesnCVz2WoSylz6Oi70Clt17haGBPjeXHbqf1e7t3G0b8biqHv76NBL072KqwHJ3ZTvRoPxQKdFFqjBdPDom8NCZ4dgsR+q5EZwlOYHlCv6SZBVfcOq4J/4zKq+xOCOt9k6RtqOwBnvBleJwXQiizxdUyDuE4JmGCmz4TFk4os8jKM5mLsxDPmG8BY/eP/5vSfOU7HI5FphNGssksoURv7yrACYqYp9Mzz4WHfNrY1yd8BwVLBKW42qSMyB+OO+Q30aXpMJsg/O5iRdb8CDgPmD2X/x97NXr7x1iKHCCHROILMsUtYLY/oX6P+KZRGFyhMXClZmleegqg8Pl6DZirkXpOvD6zTcTm4Pe3RVySBXSbTepKA1UYuUN6kuL/WqyGHrKG+LOTAv6ZHy0ba6zlfo0oJirZ5ENFxSBRMWgIEgOmhvLnUUMFGE6fAzPqLo41Vi4gdn9IZiCFMhHqHpmqCN/vq3dxdnL04NcSSumlqT9swlqLbS2AeW3t7KrcfjU9DTGcZR0RjS9GG1otz3TUwT41HH52mixuBZ5hL1Ct02DS3Qqdi0K2ACcDx8B7sm/mr1s3D7+tr3GHYzl+42cL84rLNhXA3OUyJ3rNYwfwwyDZoAYVGBlqiUcnDUCG4PNCRGs3ee+sjdu7qBxOXbjQnjLMANY+kb1+56NDdREZW/pWyP4V7mB8rGln5G99aa4NBt3cuwNhI1Uk4BmW5QbgsK2dzdIVX8MoLk++g9MXDYwmAzXEuePckoycDhE++o3IKreV4N/hvbHO7SKU43jBuVqgwg1mCGkd7EcutXsDHaUirs0j93u9QJeXWPXMtJLbfSsWOgLeVsEp4zHGd9eCTWYs7LXC5pCdxQzJisDIO0oOiZCcmWw5pGRg8GcYSmsYUZyFwtUxt8jYDjwRjCXtoZ+J+FjKN86+eRMrili0UURDJ2GmXqn0UEboIPmzFhWQ1iEjJ+wJFWcrLAHCoTOj3ZqUiLMhRDZHY2AifzYwwYJiMxnhv9IXN9EaQqlfPlQiXq/TKeLxZpuLy+nl8H4SpYLnBHSM6fvzv7/dR/+friHfWBjcSTCSh1wCvwTOg0SDF+aj2lKooDe7oT3jwWvYYyKZuXr6mRjfSrD7AHhpjnAln6XzKjT16/OXv1+p3/4uyt05B8C+xMcTkDnNrbuFCzsQMH+4CthNzg4Ap9q7jKnt7AWxMO1nq0Y+LAtGd3odnoS1Fy3R78Knn1/Lfzk5enb9kfhB+w69CmA+s1edTHGrTPhVEqnJgTcQRuja4BBmZFaXg9Er/A+gN7AzvNt/tNmkfi020LDOFOaE+Aze1STHDH+Y++mK6YiW+/xVYfdrf6iVw5lKbq+fGOHmA8xDw8AUaOOfTiFMSPKMu8vAtwXw8ErFW7/RAos0YJndzYoPfTvx6G6uYQc67ijz9ETkEtALCIKuL8C7FrEATaXopvDOZ9ZCDDtU/GwNmSCcb8EP+cdfIBY3Vg4/tktLsxflepgCYRf/32qTPQWTteP94dsKcwdo6+q07jArAgyXAAf4hy8eTpny1B0GBrzXgyYbSruU1QvzsG7FVCZpub2JlarYs/bxUMb9L2J7UMxz4K8AjkJYBzRcINF1EG/jZv+n3MZ4IAGDiHjsgUVaIGnlQ5mmnLm8edg54R5/UqPnrLu5pRaDZ9445ejUrtd43LABPnCVv+Hvkhwxr0kuY9mbIa+U9BL20Ft5xUyRnbvIxK48Mq1wQ2RZClYKeT5oqKNVoM17q2KBGZqR6YMzkav5zMDGV2iwRxZ5imeR8hX0XgOODWjzfPN5s4CthOuSg26HTUAjrgrShdWXGVeWhNJrJLfknTZWxMEftiNu7uIn4GK7K3n3nb2/lEJiYM0t3dvu8BAFQ1favbdtOfM3ljp0bXF+kiB/fCDEWPJj+XabFW/9Nwabv/GuGaQnfuym/cHia3QJrbXVqPInsaA3fAiXGUFB/qoe5dS+zxfv0ZK7kkkpZmy14yBv83ZFxbMk5UPwVroUcj0ZdlRodTdFVVAJrjsZwrUBEbpDT6AUQjLwI3sBJpinAAhZu0RvqD30l9cTrnJO6/Wml/iToWJ+oamN9TYtUaUY4/XNmEEaoTvG46kYR/ldGofIGpnQZ6ZDkF//C3zZwYQlB3R4915vBrWgwTUogbaqgq0xqCsY/hJAw2IK5INplsMb6HBSsiXdBtTYd9tgqj9P1nKjF80aWXOhMwXzBGJRBfG3JTZvbldloiNZp9iXLpJ36pXvCmoTHuT4QalOAzqFgDsF/BVNToUhR/k2TiVrqB9CswN5FiWpNWtDItRpEGiSBl0BRYDCQBZdWusjYcyEoOjAVA4wg9nG6IDWXBQ3coJQORNhwruKSLXA951AXdIQiKf6uSzpQ17Zxpk6BG4bQKf6alPnDpaTSgk/Vvr5VNyNfpSTmuFNSj0xlJQOESlYAPD2oZ3JYiX0z+glV4UovFakd5JObQhouV0aO2lrAqIBxbcvSgWE69nvb/8ZnJ+BOF6jr3YqPkNXm3Kfq27OyCT1FZiWU24C0NBK4GqOQg59nbhJ+gFA1a4ab+tqwwACOT8xJVYtvQEgSwWK5sGAtQviHzFDwZqtct89Cei2+H2d2uynJLY7MlehWXtlG3SO4rXTMswy97Y62clCcij6t6uiknuMsKG/RU4L5eB8ab5eCujTi3Q3g9XtqgNDjq3IkpBABQJRO8N8SrCHhMC50cuy/P3pzSY+SY5vN9GwFWLIYw3zZAjGwbPpgXCx39Sx0/qfN3b+HifQgLbBeHtDacl2aWrdUoltSxaRPvHV0NoQN4mMexXM9DCUYfBtlJP/qoGXEaHs9qNhahVOs04ZIZ3suGZXUChfLRRkrn70eNBfCIzt5tBibe0EkiY9MqmT/q7LTAzGp9mFsZ5cO1XvpRiPSEqdZUdgjTgr0VGRll38N/hjgON3U01wr1v9vmv8rODfY28CxewB1eZloO26UyFA5pA2mlMvaXwMIsYdhSLYJ3DWC7S18rBdlVmNPaFG1GSC9NhCHCdDCahUzZftzhfYs93dQMl23XGbZz59DGpMbpZZuAefkp5RAE4zMVT7gQN1+loQ2aR3kkYxAhbkbZEN2RwIFXWZqnQRr/7mYpnh49fTY5+tPkyV+MBSQ3ch7FAFQxlLt2XUEcqSQ/SxYpD+NkS7pjYhO3PK0rR3J35xZY7aaDO3lgrGhhjFZ9WJEi5Er+cl3hBSwBycmTqmK+pcmx3WfocZMMCCPWOVz5JtyFcTQ4DAyOJAeNsYLomBoansuULuLcpLFsxT41ZWqbiuRPY5mnTapRhcchWngtlqmtA7ag4mki3NMdhOOWX410LoIO6biG6NiMtoNkbglLk/K1kkEEBpsfte9sqbmRBmcIHFN8yrzOFWZkmHd35vKwY2O+1giGRlCzOOkey/hD9zIG5bcOvZLfTGmiMWXzy36VssuWBSalDYRBAAo9V2eL0/Ump0gXTqUuqKRJ8w+WQ37o4hAzaWzGNk6O1zsWL9KnzB9djgETt6Nwp6J1dxeYs50yNwYkLisEZhhDwtfEFpdHM8tJ1N7kpy+nPx4dzRqbTbvSbC+exiXZ3ccIyYwSU80VM+VqPzkBkbXc4sdOYaSd0YwbCdZkHLs7TXtzpZ0cs2TD0T29rY3EShRH0PHjp8rZaH2jorOAvlMxYNyvY8w+qb21vFbQRg+bnyVZQ3005niPn167lcqVz+WWqN/e1+NarIwtZrOBoxKjYLVOQwfqUfrnZ/bTLpqCDYXBcLC9KtFXM1+q7WCBJkzbDy3felqBgbmQwJhdH6RcOinMWT2Q6hZ2OGkKkx7D5y55sE7FpMrdWkDgwe+A7+7ai1JLqu5ehrrre++FKG3hIdBhDO/wK70QhPL46ahjueqGcmM5nJp7J0178FgfOFX9Q4eYY7fGv1wuDFm5/GtzSk7oo5O/2crcRCpsfALmUrTMX3fT04ZmqISJC/1tlRpS1GKB4eI9H+81dSkg2wwk12bB1VdtNd4Ij0DrLi1t8lcw/e1TbDOuj+TMmkYZddnnSDm7mA1ccDuh910fG1YMUFVv0NTE8LEeYRCjquiuPjBieKBdStwqDrBJOSq2rSk454vGDq22X9hxIotl35dn3ibd1PmTqt+w6AR3Uby5R9jp9lPCTveTvx0y2LEMRdIvibQQ9ZKMbkYrtei0JkgZ+N83zu7QiwQ3DHdp586oZsUOrp/G7J2t80wpp8ne0ZkPzdDNfi6bYXb/ktybFUW/8FsUBPGTkDHy0rb6ZpmMCmZLLq/s+6J8WNVd2sm0ii5rs3SKJ6+6vlN3y/eb1ZIt33Nf4WCr1m3YZcN+raMGur48gC3wqxxA0A376xxL0A37cw8raEJrl/vXiy873YrK4kjn78Hs7PlAH+zLjcrKoELfx0dyV/lp16B4aEGy3JmVug9r1dv/DzICCF2YeuKAYxcHYmhsshEWQWuhqLiCPqwAHRnEBepXIXd+1MLQGx90NULeMCJ/OnKASyVh+XVuhiEVvx++891UnkkslfSq7wwFaW2uurHKcFxWguh7gMeelRpnETTQGSxpORiyVFEHRnvdBzp/tAp61dvVdrRzuVVS1gV86jEVsx7Ad72fyzkHKvz/Mu2LMiO+SmNiRmsruh81yzhNljoKWZXxGnr3WJcXzPzaZoGq/Du6pTJKuIgIWBZNzs9avH4al0dr3JvCVEqssk8jMVjXCmYT0iQxosFBnjLnhY85QuUJQw/x4zNvzyBroM2aGfLZ7obyg22IB3vcn0h3nRrXVESHtWrozu+a3I8jN3j0i1caBfQNRrVnVx9i1Db8Wjbi4WCah4NpHg6meTiY5uFgmoeDaR4Opnk4mObhYJqHg2keDqZ5OJjm4WCah4NpHg6meTiY5uFgmq9/MA3nfyLM5qCzjAceIDfhEQhR4vulG/dIXOQyCTEICNYWngwiNiCYObIXaTVzkgcd/tJ5FIxnAX3Nk2AY2tc+D+bTcLSnwmAfH+MSWPa1hS0yW95cPpnOygQhv8SoN11dHs2Y2AbAoFbri8EYRxh7c3Mjzx7cMXJSrqPOsnQ/k7doLNnRS5xIcIeINJcKUz1zGT5jfwtstXphMWK4Ay0bzfvuO6foFjEYIXZ4IFLtuBI+5vpuTOuWFbSQeMz1w2lID6chdWyQeMp5FIDPV56Pjuqr+1h0PAG9TEfiEepVShHvmGx4VT+d/ktyeV+WqfuiPNyXZNmqHBoeR58U68H00vAbCizhPBhb5oKrEgYYh5REAbpxjgqcvyoy2ybul+ScPjGjNOjAzDiIbbw+K48DI5gUzGCKAWybuRlMn5Vjm7zS4A5GtwkWPujfNOAkOCJnP3IE7PAOPAWceGhvYaUSmeBRcpcDVNRTksjpHnFFKqTAZ1P6XzKAXchFv8dHbGkdH+EKZkEEmDzxjgaI5CbVEZLVShhYQEujkTsFskuhj+n0H56oqd/nEWCMu38D2O3RCy5iAAA=
