"""IdeaRefiner -- Refine the user's existing plan, decision, or draft through relentless refinement. Use when the user wants to sharpen or stress-test their thinking.

Generated by the rapp skill from idea-refiner. The RCI capsule at the bottom of this file carries the full original; `toast.py convert` restores it byte-exact."""

import json
import re
import sys

try:
    from agents.basic_agent import BasicAgent
except ImportError:  # running OUTSIDE a brainstem -- stay executable anyway.
    class BasicAgent:  # noqa: D101 - minimal stand-in, same contract
        def __init__(self, name=None, metadata=None):
            if name:
                self.name = name
            if metadata:
                self.metadata = metadata

        def perform(self, **kwargs):
            return "Not implemented."

        def system_context(self):
            return None

        def to_tool(self):
            return {"type": "function", "function": {
                "name": self.name,
                "description": self.metadata.get("description", ""),
                "parameters": self.metadata.get("parameters", {})}}

# The procedural layer, verbatim from the source capability.
INSTRUCTIONS = "Assume a plan, decision, or draft already exists. The job is to sharpen it with questions, not draft one from scratch, and ensure that I have fully thought through the entire plan.\n\nWalk down each branch of the decision tree, resolving dependencies between decisions one-by-one. For each question, give your recommended answer.\n\nGroup each turn's questions by branch: 2–5 related questions per turn, sized to what that branch needs. For each question, provide your recommended answer. Wait for my feedback on the whole batch before moving to the next branch.\n\nIf Work IQ is available, look through Work IQ for any facts before asking me. Put every decision to me directly and wait for my answer.\n\nDo not act on it until I confirm we have reached a shared understanding."

# Ordered commands lifted verbatim from the capability's own documentation.
STEPS = []


class IdeaRefinerAgent(BasicAgent):
    def __init__(self):
        self.name = 'IdeaRefiner'
        self.metadata = {
          "name": "IdeaRefiner",
          "description": "Refine the user's existing plan, decision, or draft through relentless refinement. Use when the user wants to sharpen or stress-test their thinking.",
          "parameters": {
            "type": "object",
            "properties": {},
            "required": []
          }
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs):  # toaster:generated-perform
        return json.dumps({"status": "ok", "instructions": INSTRUCTIONS,
                           "inputs": kwargs,
                           "note": "Prose-only capability: follow INSTRUCTIONS "
                                   "with the given inputs."}, indent=2)

if __name__ == "__main__":
    #     echo '{"arg": "value"}' | python3 idea_refiner_agent.py
    #     python3 idea_refiner_agent.py '{"arg": "value"}'
    #     python3 idea_refiner_agent.py --tool          # emit the JSON tool contract
    _a = sys.argv[1:]
    if _a and _a[0] == "--tool":
        print(json.dumps(IdeaRefinerAgent().to_tool(), indent=2))
    else:
        _raw = _a[0] if _a else (sys.stdin.read().strip() or "{}")
        print(IdeaRefinerAgent().perform(**json.loads(_raw)))

# rci-capsule:v1:H4sIAAAAAAAC/3VWXZOiOBT9Kyle9qHtVhRFu2q3ys8WUXtUbD92trZCCIJCgkkQYWr++160nZmt2vVBA7k5OffccxO/aThVARfaK0ujqKJ5VBIRJirkTHvVltQPGUUqoCiVVPwmEb2GUoXsgJIIswryKAklxFYQF8gT2FcQLHh6CJCgEWUqolLCsISJ4fEFrSVFWUDZD1CUYaYkUhzJAIsEZgBKKgELnxWVJSANBXyH7AQbv2gVjV5xnACy9vrnXxUthPGDfshgZUpK+jCrdaVMY4rw/7PFkaDYy+95yRfkAKsjd1H4L0ahQlmoAnROgVCJXUGMq08IDgr5gscIlMOKBBWEmYcok6kopcMKWSjAFwgCijm8KeX5qVOpAygTQnDJ8uUr+8o2ODohj2cMUUwC5ArM4If7t+BHFgg0ohUQV/LoUpbEo8DVo4yEVCKXqowC9Ue0LHk+u/kz/LygEQhwg35kVEGHECjmPBWASHgcl1AepCIzKm6k3oBvcl+lUsHADD/kQG7+SfIV1b+m9ZreaJYGwAogfkYlUO1yaQXJsIAZUDgr9bmJ9Jkko9ST/0kwEfwSev/PEW0w1MmHhXGOfIBxMTkhfndaFvCIIresD0gDQRTF/KYakCgDGL0+ONyytXy04eKErEXpBXzBYYTdCPSOOD/9KN4jpNwVM9gWEyUfG2BZGhbFoPeXVCF6oSL/pXocZpAHdScKbFF6JvslgV+EH/Cb2wC6zAZCUrBLBK4inPmhiFFG7wYTpWKlIDfjwiAFfYRUgP3ZOVFIwJj00S4MxzDWLI/ie6sLiEmwgNcKFmqv3zRQHcqmwrLbvn2vaIKeU+Ds3XtP5UkJwN0jZKHBNFhYQQbxPTgBc1JxKaO/aaBGFJUDt2XAmrEhre790682PpzZfuoseoNZdScmq/5i/DEZGtw494ncL9dWc1xXo6S9SbaFncvhdVQ1LNoORua+Hegf27fpvq5a1Eya9a1HzdyakXxwCTbnbbHeOuw6EvquukvG6XH6lEzyabHat3rySH1742/z02zbl/mQiYHXt0/JxDGP0258dscsWvWvvWJ4tE3SbZhpay8nhdsYvudsPp7Ol0686LSMg7MeRZutnReb/nAtqsdae1f0nvTa3HAvjb2aHa52VRj2oO+K01kd9c7VLS7n1bha5LmPfdxMrm1nycddm/OkkR9WlzHFvZN1YvP0yeKt98n8fJosnXfPXtFp1ptbq6uxNrLqRO+STMzGqX0kZmPHBrGX451xanxx1/aQtNfC68+z9tDUrWA+vATr86TePX+879LL6DwZtvvG8oL78tyq46TtHZ1lJ/DPDqmOHL3VHxWr5K0na0V3bR/Icc5VvxZ6fIw7jfZ5sbTN5nhB9PzUCA+q0XmqbptbT/K9arYD67rfmdHHqRp678N3nRwi5qR+PLWk+XSuN9becGxuk4/xpI3771FGRmnSrTV6ZsIWqujkzJqv1tdV9+Ngrd5Ud/c2XKwXzQ1zuvaX8fHUnBSNZdvubQ/96qXrrAcLC28Lf0PcZFacQntM9urC62s+wDDHWt6MBCNve86UsQPGSo+VPVrvt0ZQbZpGYC43g5kz6i+6znswWSSOOypS1ZX61U1WGzWULv5g+f5k6bjHvjStajZardy3wWw4AO/+Dh3jh3DV3VtpZVvT6UvswVvowXqzBe88k/pN3adNbDQo1nUX67TeqteIQbBu+q120/U6LaJ3vA416+0mcTsNomOz5pO251JT+35rJX6BTRiBXf7Uykvr9dZQr7/sCOcBnDHqPvH8Bz7AvaJBlwoSAg39pVayitIDPMBBip/Fj56XuVQ0/hsAFJyDj+NB4cPnHQuw8v6XAFAA5/s/O5xk9jgIAAA=
